import Foundation

/// Written on first run, and the documentation of every key: a config
/// that explains itself. Mirror any new key here.
extension Config {
    static let template = """
    {
      "$schema": "./config.schema.json",

      // Global hotkey: cmd / opt / ctrl / shift + a key. Applied at launch.
      "hotkey": "opt+space",

      "appearance": {
        "width": 680,
        "cornerRadius": 16,
        "queryFontSize": 26,
        "rowFontSize": 14,
        "topOffset": 0.2,
        // "font": "JetBrainsMono Nerd Font",
        // "searchIcon": "magnifyingglass",  // SF Symbol, or any text; "" hides it
        // "placeholder": "Search apps…",
        // "colorScheme": "dark",      // omit to follow the system
        // "accent": "#7C6CF0",
        // "background": "#1C1C1EEE",  // tints the wash over the card; "#00000000" turns it off
        // "foreground": "#FFFFFF",
      },

      // A theme lists only the appearance keys it changes; the rest stays as above.
      // Switch with a command below — one line to rewrite, nothing to duplicate.
      // Themes also load from `themes/*.jsonc` (same shape, named after the file), so an
      // imported theme is a downloaded file — see the "Import Theme" command.
      "theme": "system",
      "themes": {
        "system": {},
        "midnight": { "colorScheme": "dark", "background": "#000000", "accent": "#7C6CF0" },
        "paper": { "colorScheme": "light", "background": "#FFFFFF", "accent": "#0A84FF" },
      },

      // Plugins are entries here: `run` is a shell one-liner, so `open` and `./script.sh` work.
      "commands": [
        { "name": "Toggle System Appearance", "icon": "circle.lefthalf.filled",
          "run": "osascript -e 'tell app \\"System Events\\" to tell appearance preferences to set dark mode to not dark mode'" },
        { "name": "Import Theme", "icon": "square.and.arrow.down", "subtitle": "URL from the clipboard",
          "run": "mkdir -p themes && curl -fsSLO --output-dir themes \\"$(pbpaste)\\"" },
        { "name": "Theme", "icon": "paintpalette", "commands": [
          { "name": "System",   "run": "sed -i '' 's/\\"theme\\": \\".*\\"/\\"theme\\": \\"system\\"/' config.jsonc" },
          { "name": "Midnight", "run": "sed -i '' 's/\\"theme\\": \\".*\\"/\\"theme\\": \\"midnight\\"/' config.jsonc" },
          { "name": "Paper",    "run": "sed -i '' 's/\\"theme\\": \\".*\\"/\\"theme\\": \\"paper\\"/' config.jsonc" },
        ]},
        // { "name": "Sleep", "icon": "moon.fill", "run": "pmset sleepnow" },   // SF Symbol
        // { "name": "Files", "icon": "\u{f07b}", "run": "open ~" },              // any text works too
        // { "name": "GitHub", "icon": "globe", "run": "open https://github.com" },
        // { "name": "Style", "commands": [                        // submenu, written out here
        //   { "name": "Dark", "run": "dark-mode on" },
        // ]},
        // { "name": "Projects", "menu": "./plugins/projects ~" },  // submenu printed by a script
        // { "name": "GitHub", "prefix": "gh ", "icon": "globe",   // "gh swift" hands "swift" to $1
        //   "menu": "./plugins/gh-search \\"$1\\"" },
      ],
    }
    """
}

extension Config {
    /// Editors pick this up through the `$schema` key in the config: key completion, type checks
    /// and typo catching (`additionalProperties: false`) for free.
    /// ponytail: hand-written and kept next to the types it describes — Swift has no schema
    /// generator worth the machinery for eleven keys
    static let schema = """
    {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "title": "syures config",
      "description": "Generated by syures on launch. Edits here are overwritten.",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "$schema": { "type": "string" },
        "hotkey": {
          "type": "string",
          "default": "opt+space",
          "description": "Global hotkey: cmd / opt / ctrl / shift joined by +, then one key. Read at launch only."
        },
        "appearance": { "$ref": "#/$defs/appearance" },
        "theme": {
          "type": "string",
          "description": "Name of the themes entry layered over appearance. Omit to use appearance as-is."
        },
        "themes": {
          "type": "object",
          "description": "Named overlays: each lists only the appearance keys it changes.",
          "additionalProperties": { "$ref": "#/$defs/appearance" }
        },
        "commands": {
          "type": "array",
          "description": "Entries shown alongside installed apps.",
          "items": { "$ref": "#/$defs/command" }
        }
      },
      "$defs": {
        "color": {
          "type": "string",
          "pattern": "^#([0-9a-fA-F]{6}|[0-9a-fA-F]{8})$",
          "description": "#RRGGBB or #RRGGBBAA"
        },
        "appearance": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "width": { "type": "number", "exclusiveMinimum": 0, "default": 680 },
            "cornerRadius": { "type": "number", "minimum": 0, "default": 16 },
            "queryFontSize": { "type": "number", "exclusiveMinimum": 0, "default": 26 },
            "rowFontSize": { "type": "number", "exclusiveMinimum": 0, "default": 14 },
            "topOffset": {
              "type": "number",
              "minimum": 0,
              "maximum": 1,
              "default": 0.2,
              "description": "How far down the screen the card sits, as a fraction of screen height."
            },
            "searchIcon": {
              "type": "string",
              "default": "magnifyingglass",
              "description": "Shown left of the query: an SF Symbol name, or any text (emoji, Nerd Font glyph). Empty hides it."
            },
            "placeholder": {
              "type": "string",
              "default": "Search apps…",
              "description": "Placeholder in the empty query field."
            },
            "font": {
              "type": "string",
              "description": "Font family for the query, rows and text icons. Omit for the system font; an unknown family falls back to it."
            },
            "colorScheme": {
              "enum": ["light", "dark"],
              "description": "Omit to follow the system."
            },
            "accent": {
              "allOf": [{ "$ref": "#/$defs/color" }],
              "description": "Omit to use the system accent."
            },
            "background": {
              "allOf": [{ "$ref": "#/$defs/color" }],
              "description": "Tints the wash over the card: opaque at the top, gone by the bottom. Omit for black in dark mode and the system window background in light; #00000000 turns it off."
            },
            "foreground": {
              "allOf": [{ "$ref": "#/$defs/color" }],
              "description": "Omit to use the system label colour."
            }
          }
        },
        "command": {
          "type": "object",
          "additionalProperties": false,
          "required": ["name"],
          "oneOf": [
            { "required": ["run"] },
            { "required": ["commands"] },
            { "required": ["menu"] }
          ],
          "properties": {
            "name": { "type": "string" },
            "subtitle": { "type": "string" },
            "icon": {
              "type": "string",
              "description": "SF Symbol name, or any text to draw as a glyph — a Nerd Font icon, an emoji, a letter."
            },
            "run": { "type": "string", "description": "Shell one-liner, run through /bin/sh -c from the config folder." },
            "commands": {
              "type": "array",
              "description": "Submenu written out in place.",
              "items": { "$ref": "#/$defs/command" }
            },
            "menu": {
              "type": "string",
              "description": "Shell one-liner whose stdout is a JSON array of commands — the submenu it opens. Same shape as this file, so entries can nest further."
            },
            "prefix": {
              "type": "string",
              "description": "Typing this at the root hands the rest of the query to run / menu as the shell parameter $1, on Enter — a script of your own gets it only if the one-liner passes it on: './plugins/gh-search \\"$1\\"'. The longest matching prefix wins."
            }
          },
          "dependentSchemas": {
            "prefix": {
              "not": { "required": ["commands"] },
              "description": "A submenu written out in place has no script to hand the argument to."
            }
          }
        }
      }
    }
    """
}
